Адаптивная сетка для главной страницы
htmlacademy-adaptive/1579099-sedona-21 pull request #8
Opened 2020-12-02 13:36 UTC by darmmw

2020-12-03 07:20 UTC, mikhin requested changes

2020-12-03 07:20 UTC, mikhin commented on source/index.html
> +      <div class="page-main__logo-content logo-wrap">
Непонятно зачем нужен такой блок)

2020-12-03 07:20 UTC, mikhin commented on source/index.html
> +        <img class="logo__welcome" src="img/welcome.svg" alt="Welcome" width="115" height="28">
Непонятно где родитель этих элементов)

2020-12-03 07:20 UTC, mikhin commented on source/index.html
> +                <div class="reason-card__city-part1">
Все имена классов с числами в таком духе это сразу нет)

2020-12-03 07:20 UTC, mikhin commented on source/index.html
> +              <div class="reason-card__wrapper reason-card__city">
А зачем чтоб один html-элемент был сразу двумя БЭМ-элементами?

2020-12-03 07:20 UTC, mikhin commented on source/sass/reason-card.scss
> +  height: 211px;
Опять появляется много объявлений height и кажется уже опять проект сразу опять перестает быть гибким. Такое у нас уже было в первом проекте) Здесь точно нужны высоты а не паддинги? Эти высоты позволят пройти проверку на переполнение контентом, если контента станет в два раза больше?

2020-12-03 07:20 UTC, mikhin commented on source/sass/reason-card.scss
> +.reason-card-close-wrapper {
Если это отдельный БЭМ-блок, то он должен быть в отдельном файле.

2020-12-03 07:20 UTC, mikhin commented on source/sass/reason-card.scss
> +  margin-top: 100px;
Если это отдельный БЭМ-блок, то на нем не может быть CSS-правил внешней геометрии.

2020-12-03 07:20 UTC, mikhin commented on source/sass/variables.scss
> +$mobile-width-only: 767px;
Такой брейкпоинт не нужен совсем, т.к. по умолчанию стили у нас уже и есть для мобильной версии)

2020-12-03 07:20 UTC, mikhin commented on source/index.html
>      <main class="page-main main">
Не хватает какого-то класса, который бы ограничивал ширину контента на странице до нужных размеров по дизайну и ТЗ

2020-12-04 09:41 UTC, mikhin requested changes

2020-12-04 09:41 UTC, mikhin commented on source/sass/content-wrapper.scss
> +  margin: 0 18px;
Во-первых на БЭМ-блоке не может быть правил внешней геометрии (марджин, позишн абсолют и т.д.). Если непонятно почему, то давай обсудим, это прям важно понимать. Так что скорее всего это паддинги.

Во-вторых, этому классу не нужно разве установить максимальную ширину?

2020-12-04 09:41 UTC, mikhin commented on source/sass/reason-card-close-wrapper.scss
> +.reason-card-close-wrapper {
Оч странное имя класса. Какая у него функция?

2020-12-04 09:41 UTC, mikhin commented on source/sass/reason-card.scss
> +  height: 260px;
Ну, и ширина в итоге осталась везде) Давай ее уберем?)

2020-12-04 11:23 UTC, darmmw commented on source/sass/content-wrapper.scss
> +  margin: 0 18px;
максимальную ширину для каждой версии, верно?

2020-12-04 11:23 UTC, darmmw commented on source/sass/reason-card-close-wrapper.scss
> +.reason-card-close-wrapper {
Добавила приставку close тк по моей логике серые карточки закрыты, а синие открыты (в них есть доп элементы) 
И на эти закрытые карточки я повесила класс, чтобы можно было с ними как-то взаимодействовать, не затрагивая открытые

2020-12-04 11:23 UTC, darmmw commented on source/sass/reason-card.scss
> +  height: 260px;
ширина или высота? если высота, то я оставила ее только на img или обертках img, кажется это не должно мешать гибкости сайта

2020-12-07 08:25 UTC, mikhin commented on source/sass/content-wrapper.scss
> +  margin: 0 18px;
ну да, иначе в чем его «контейнерность»?) Сейчас он все также разъезжается на всю страницу)

2020-12-07 08:25 UTC, mikhin commented on source/sass/reason-card-close-wrapper.scss
> +.reason-card-close-wrapper {
Звучит резонно, но давай эту функцию унесем в блок карточки и опишем там её через модификатор)

2020-12-07 08:25 UTC, mikhin commented on source/sass/reason-card.scss
> +  height: 260px;
Окей, справедливо)

2020-12-08 08:51 UTC, mikhin commented
@darmmw, вижу в консоли браузера ошибку насчет файла-нормалайза)

2020-12-08 10:36 UTC, mikhin requested changes

2020-12-08 10:36 UTC, mikhin commented on source/index.html
> +    <link rel="stylesheet" href="sass/normalize.scss">
@darmmw, не, а мы же не должны хотеть такого — подключать одни стили из одного места, а другие из другого. У нас же в итоговой сборке не будет папки `sass`.

2020-12-08 10:36 UTC, mikhin commented on .stylelintignore
> +source/sass/normalize/*.scss
Зачем?)

2020-12-08 10:36 UTC, mikhin commented on package.json
> +    "normalize-scss": "^7.0.1"
Зачем?) В рамках проекта не должны хотеть что-то сторонне устанавливать)

2020-12-08 10:36 UTC, mikhin commented on source/sass/normalize/_vertical-rhythm.scss
> +//
Это что-то очень странное и непонятное. Подскажи, для чего это нужно?)

2020-12-08 10:52 UTC, darmmw commented on .stylelintignore
> +source/sass/normalize/*.scss
потому что stylelint видит ошибкой @function @if и тп в этих файлах

2020-12-08 10:52 UTC, darmmw commented on package.json
> +    "normalize-scss": "^7.0.1"
это установка normalize.scss

2020-12-08 10:52 UTC, darmmw commented on source/sass/normalize/_vertical-rhythm.scss
> +//
это установка normalize.scss

2020-12-08 17:08 UTC, mikhin commented on source/sass/blocks/content-wrapper.scss
> +.content-wrapper__card-city {
Этот БЭМ-блок нужно отрефакторить в следующем ПР и сделать так чтобы он не знал ни про какие карточки города, карточки моста и тексты бронирований. Почему так — потому что каждый модуль в программировании (читай БЭМ-блок) должен соответствовать принципу единой ответственности (https://ru.wikipedia.org/wiki/%D0%A1%D0%B2%D1%8F%D0%B7%D0%BD%D0%BE%D1%81%D1%82%D1%8C_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)). Что это дает: сейчас на примере этого блока можно наблюдать как он «связан» с другими блоками и контекстами собственного применения. В результате такой спроектированной системы код получается связанным, путанным и хрупким. Это означает что правки в одной части системы приводят к правкам в другой, кажущейся независимой, части системы. Это значит что время на доработки, внедрение новых фич, поддержку кода, увеличивается, как и стоимость проекта. Это не круто. Если следовать принципам проектирования, и, например, писать несвязанный код, разделенный на независимые модули (чем являются БЭМ-блоки), то система получается простой, понятной любому, предсказуемой, и легкой в поддержке =) 😅

2020-12-08 17:08 UTC, merged